import { Container, Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "./theme.config.css";
import AuthProvider from "./auth/AuthProvider";
import QueryClientProvider from "./QueryClientProvider";

const poppins = Poppins({
   variable: "--font-poppins",
   weight: ["100", "300", "400", "700", "900"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <AuthProvider>
            <body className={`${poppins.variable} radix-themes antialiased`}>
               <QueryClientProvider>
                  <Theme accentColor="violet" grayColor="sand" radius="large">
                     <Navbar />
                     <Container>
                        <div className="p-5">{children}</div>
                     </Container>
                  </Theme>
               </QueryClientProvider>
            </body>
         </AuthProvider>
      </html>
   );
}
