import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "./theme.config.css";

const poppins = Poppins({
   variable: "--font-poppins",
   weight: ["100", "300", "400", "700", "900"],
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${poppins.variable} radix-themes antialiased`}>
            <Theme accentColor="violet" grayColor="sand" radius="large">
               <Navbar />
               <div className="p-5">{children}</div>
            </Theme>
         </body>
      </html>
   );
}
